cache:
  paths:
    - .m2/repository

stages:
  - clean
  - test
  - install

clean:
  stage: clean
  script:
    - echo $JAVA_HOME
    - mvn clean
  only:
    - master

test:
  stage: test
  script:
    - echo $JAVA_HOME
    - mvn test
  only:
    - master

install:
  stage: install
  script:
    - echo $JAVA_HOME
    - mvn install -DskipTests
  only:
    - master
