cache:
  paths:
    - .m2/repository


stages:
  - clean
  - test
  - install

clean:
  stage: clean
  script:
    - 'mvn clean'
  only:
    - master

test:
  stage: test
  script:
    - 'mvn test'
  only:
    - master

install:
  stage: install
  script:
    - 'mvn install -DskipTests'
  only:
    - master

