variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

stages:
  - clean
  - test
  - install

clean:
  stage: clean
  script:
    - 'java -version'
    - 'mvn clean'
  only:
    - master

test:
  stage: test
  script:
    - 'java -version'
    - 'mvn test'
  only:
    - master

install:
  stage: install
  script:
    - 'java -version'
    - 'mvn install -DskipTests'
  only:
    - master

